CREATE VIEW [cm].[DiskDriveView] 
AS
SELECT [dd].[objectGUID]
      ,[dd].[ComputerGUID]
	  ,[c].[dnsHostName]
      ,[dd].[Name]
      ,[dd].[DeviceID]
      ,[dd].[Manufacturer]
      ,[dd].[Model]
      ,[dd].[SerialNumber]
      ,[dd].[FirmwareRevision]
      ,[dd].[Partitions]
      ,[dd].[InterfaceType]
      ,[dd].[SCSIBus]
      ,[dd].[SCSIPort]
      ,[dd].[SCSILogicalUnit]
      ,[dd].[SCSITargetID]
      ,[dd].[Size]
      ,[dd].[Status]
      ,[dd].[Active]
      ,[dd].[dbAddDate]
      ,[dd].[dbLastUpdate]
  FROM [cm].[DiskDrive] dd INNER JOIN [cm].[Computer] c ON
	[dd].[ComputerGUID] = [c].[objectGUID]
